services:
  doctrine.cache.apcu:
    class: Vainyl\Doctrine\Common\Cache\DoctrineApcuCache
  doctrine.cache.memory:
    class: Doctrine\Common\Cache\ArrayCache
#  doctrine.cache.redis:
#    class: Vainyl\Doctrine\Common\Cache\DoctrineRedisCache
#    arguments: ['@redis.database']
  connection.factory.doctrine:
    class: Vainyl\Doctrine\Common\Factory\DoctrineConnectionFactory
    arguments: ['@connection.storage'];
  doctrine.event.manager:
    class: Doctrine\Common\EventManager
  database.factory.doctrine:
    class: Vainyl\Doctrine\Common\Factory\DoctrineDatabaseFactory
    arguments: ['@connection.storage', '@doctrine.configuration.orm', '@doctrine.event.manager']
